import type { Metadata } from "next";
import "./globals.css";
import { cn } from "@/lib/utils";
import { Inter as FontSans } from "next/font/google";
import Header from "./header";
import { Toaster } from "@/components/ui/sonner";
import ModalProvider from "@/providers/modal-provider";
import { NotificationContext } from "@/contexts/notification-context";
import { getCurrentSession } from "@/data-access/users";
import { UserContextProvider } from "@/contexts/user-context";

const fontSans = FontSans({
  subsets: ["latin"],
  variable: "--font-sans",
});

export const metadata: Metadata = {
  title: "Create Next App",

  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const { user } = await getCurrentSession();

  return (
    <html lang="en">
      <body
        className={cn(
          "min-h-screen bg-background font-sans antialiased",
          fontSans.variable,
        )}
      >
        <NotificationContext userId={user?.id}>
          <UserContextProvider value={user?.id}>
            
          <Toaster />
          <Header />
          <div className="container mx-auto py-12">{children}</div>
          </UserContextProvider>
        </NotificationContext>
      </body>
    </html>
  );
}
